service: menu-manager-nest
  
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-offline

provider:
  stage: api
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: ${env:DB_NAME}
    ENVIRONMENT: ${env:ENVIRONMENT}
    S3MANAGER: ${env:S3MANAGER}



functions:
  main: # The name of the lambda function
   # The module 'handler' is exported in the file '.build/lambda'
   handler: dist/lambda.handler
   events:
      - http: ANY /
      - http: ANY {proxy+}